### ISSUE TITLE
ServerRequest::getUriFromGlobals() throws exception for IPv6 local loopback address

### ISSUE THREAD

**Issue by hansott** [guzzle/psr7#193]
`[::1]` is an IPv6 loopback address

I'm proxying requests of a webpack dev server to my PHP application.

`$_SERVER["HTTP_HOST"] = "[::1]:8000";`

```
Fatal error: Uncaught InvalidArgumentException: Invalid port: 0. Must be between 1 and 65535 in vendor/guzzlehttp/psr7/src/Uri.php:615
Stack trace:
#0 vendor/guzzlehttp/psr7/src/Uri.php(478): GuzzleHttp\Psr7\Uri->filterPort(0)
#1 vendor/guzzlehttp/psr7/src/ServerRequest.php(199): GuzzleHttp\Psr7\Uri->withPort('')
#2 vendor/guzzlehttp/psr7/src/ServerRequest.php(170): GuzzleHttp\Psr7\ServerRequest::getUriFromGlobals()
```

**Comment by hansott** [comment]
Thanks for this library btw 😇

**Comment by hansott** [comment]
```
~/Code $ php -a
Interactive shell

php > var_dump(parse_url('http://[::1]:8000/api/config'));
array(4) {
  ["scheme"]=>
  string(4) "http"
  ["host"]=>
  string(5) "[::1]"
  ["port"]=>
  int(8000)
  ["path"]=>
  string(11) "/api/config"
}
php >
```

**Comment by hansott** [comment]
I'm going to try submitting a PR.

**Comment by hansott** [comment]
Created a PR to fix this issue: https://github.com/guzzle/psr7/pull/194
