### ISSUE TITLE
Invalid user agent string in headers

### ISSUE THREAD

**Issue by pestaa** [guzzle/psr7#498]
We rolled out 1.8.4 from #486 today and see errors like this one.

```
PHP Fatal error:  Uncaught InvalidArgumentException: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36" is not valid header value in /source/vendor/guzzlehttp/psr7/src/MessageTrait.php:267
Stack trace:
#0 /source/vendor/guzzlehttp/psr7/src/MessageTrait.php(203): GuzzleHttp\\Psr7\\Request->assertValue()
#1 [internal function]: GuzzleHttp\\Psr7\\Request->GuzzleHttp\\Psr7\\{closure}()
#2 /source/vendor/guzzlehttp/psr7/src/MessageTrait.php(206): array_map()
#3 /source/vendor/guzzlehttp/psr7/src/MessageTrait.php(168): GuzzleHttp\\Psr7\\Request->trimAndValidateHeaderValues()
#4 /source/vendor/guzzlehttp/psr7/src/MessageTrait.php(148): GuzzleHttp\\Psr7\\Request->normalizeHeaderValue()
#5 /source/vendor/guzzlehttp/psr7/src/Request.php(47): GuzzleHttp\\Psr7\\Request->setHeaders()
#6 /source/vendor/guzzlehttp/psr7/src/ServerRequest.php(75): GuzzleHttp\\Psr7\\Request->__construct()
#7 /source/vendor/guzzlehttp/psr7/src/ServerRequest.php(178): GuzzleHttp\\Psr7\\ServerRequest->__const in /source/vendor/guzzlehttp/psr7/src/MessageTrait.php on line 267
```

Reverting back 1.8.3 fixes it.

**Comment by GrahamCampbell** [comment]
Try upgrading to 1.8.5. 1.8.4 contained a bug.
